# series的创建

In [1]:
import pandas as pd

In [2]:
# series的创建
s = pd.Series([10, 2, 3, 4, 5])
# 自定义索引
# s = pd.Series([10, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
# s = pd.Series([10, 2, 3, 4, 5], index=[1, 2, 3, 4, 5])
#定义标签
s = pd.Series([10, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'], name = '月份')
print(s)

A    10
B     2
C     3
D     4
E     5
Name: 月份, dtype: int64

In [3]:
# 通过字典的方式创建
s = pd.Series({"a":1,"b":2,"c":3,"d":4,"e":5})
print(s)
s1 = pd.Series(s,index=["a", "c"])
print(s1)
s2 = pd.Series([10, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'], name = '月份')
s21 = pd.Series(s2,index=["A", "D"])
print(s21)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
dtype: int64
A    10
D     4
Name: 月份, dtype: int64

In [4]:
# series的属性
"""index:Series的索引对象
values:Series的值
dtype或dtypes:Series的元素类型
shape:Series的形状
ndim:Series的维度
size:Series的元素个数
name:Series的名称
loc[显式索引，按标签索引或切片
iloc[]隐式索引，按位置索引或切片
at[]使用标签访问单个元素
iat[]使用位置访问单个元素
"""
print(s.index)
print(s.values)
print(s.shape,s.ndim,s.size)
print(s.dtype)
s.name = 'test'
print(s.name)
print(s.loc['a': 'c'])# 显式索引
print(s.iloc[1:4]) # 隐式索引
print(s.at['a']) # 不支持切片
print(s.iat[3])

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
[1 2 3 4 5]
(5,) 1 5
int64
test
a    1
b    2
c    3
Name: test, dtype: int64
b    2
c    3
d    4
Name: test, dtype: int64
1
4

In [5]:
# 访问数据
#print(s['c'])
print(s[s<=3])
s['f'] = 6
print(s.head(2))
print(s.tail(1))

a    1
b    2
c    3
Name: test, dtype: int64
a    1
b    2
Name: test, dtype: int64
f    6
Name: test, dtype: int64

In [6]:
# 常见函数
import numpy  as np
s = pd.Series([10,2,np.nan,None,3,4,5], index=['A', 'B', 'C', 'D',
'E','F','G'], name='data')
print(s)

A    10.0
B     2.0
C     NaN
D     NaN
E     3.0
F     4.0
G     5.0
Name: data, dtype: float64

In [7]:
s.head(3).to_frame() # 默认前五个数据
s.tail(6).to_frame() # 默认后五行数据

   data
B   2.0
C   NaN
D   NaN
E   3.0
F   4.0
G   5.0

In [8]:
# 查看所有的描述性信息
s.describe().to_frame()

            data
count   5.000000
mean    4.800000
std     3.114482
min     2.000000
25%     3.000000
50%     4.000000
75%     5.000000
max    10.000000

In [9]:
# 获取元素个数 忽略缺失值
s.count()

np.int64(5)

In [10]:
# 用来获取索引，前者通过方法()，后者通过属性
print(s.keys())
print(s.index)

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='str')
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='str')

In [11]:
# 判断缺失值
print(s.isna().to_frame())

    data
A  False
B  False
C   True
D   True
E  False
F  False
G  False

In [12]:
# 检查每个元素是否在参数集合中
s.isin([4, 5, 6])

A    False
B    False
C    False
D    False
E    False
F     True
G     True
Name: data, dtype: bool

In [13]:
print(s.describe())
print(s.mean())
print(s.sum())
print(s.std())
print(s.var())
print(s.min())
print(s.max())
print(s.median())
print(s.sort_values())

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64
4.8
24.0
3.1144823004794877
9.700000000000001
2.0
10.0
4.0
B     2.0
E     3.0
F     4.0
G     5.0
A    10.0
C     NaN
D     NaN
Name: data, dtype: float64

In [14]:
print(s.quantile(0.8))

6.000000000000001

In [15]:
#众数
s['H']=4
print(s.mode())

0    4.0
Name: data, dtype: float64

In [16]:
print(s.value_counts()) # 元素的计数

data
4.0     2
10.0    1
2.0     1
3.0     1
5.0     1
Name: count, dtype: int64

In [17]:
s.drop_duplicates().to_frame() # 去重
s.unique()
print(s.nunique()) # 去重后元素的个数

5

In [18]:
# 排序  值、索引
s.sort_index() # 按索引排序
print(s.sort_values()) # 按值排序

B     2.0
E     3.0
F     4.0
H     4.0
G     5.0
A    10.0
C     NaN
D     NaN
Name: data, dtype: float64

In [19]:
#创建一个包含10名学生数学成绩的Serie8，成绩范围在50-100之间。
#计算平均分、最高分、最低分，并找出高于平均分的学生人数。

In [20]:
import pandas as pd
import numpy as np
np.random.seed(42)
scores = pd.Series(np.random.randint(50, 101, 10), index=['学生'+str(i) for i in range(1, 11)])
print(scores)
print('平均分：', scores.mean())
print('最高分： ', scores.max())
print('最低分： ', scores.min())
mean = scores.mean()
print('高于平均分的学生人数：', scores[scores>mean].count())
print(len(scores[scores>mean]))

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int32
平均分： 73.7
最高分：  92
最低分：  57
高于平均分的学生人数： 4
4

In [21]:
#给定某城市一周每天的最高温度Series，完成以下任务:找出温度超过30度的天数
#计算平均温度
#将温度从高到低排序
#找出温度变化最大的两天

In [22]:
import pandas as pd
import numpy as np
temperatures = pd.Series([28, 31, 29, 32, 30, 27, 33], # values
               index=['周一','周二','周三','周四','周五','周六','周日'],
               name='温度')
temperature = temperatures>30
print(temperature.to_frame())
print('温度大于30的天数：', len(temperatures[temperatures>30]))
print('平均值：', temperatures.mean())
t2 =  temperatures.sort_values(ascending=False)
print(f"从高到低排序:\n{t2}")
# 温度变化最大的两天
t3 = temperatures.diff().abs() # 计算series数组的变化的值

print('温度变化最大的两天',t3.sort_values(ascending=False).index[:2].to_list())

       温度
周一  False
周二   True
周三  False
周四   True
周五  False
周六  False
周日   True
温度大于30的天数： 3
平均值： 30.0
从高到低排序:
周日    33
周四    32
周二    31
周五    30
周三    29
周一    28
周六    27
Name: 温度, dtype: int64
温度变化最大的两天 ['周日', '周二']

In [34]:
#给定某股票连续10个交易日的收盘价Series:
# 计算每日收益率(当日收盘价/前日收盘价-1)
# 找出收益率最高和最低的日期
# 计算波动率(收益率的标准差)
import pandas as pd
import numpy as np
prices = pd.Series([102.3, 103.5, 105.1, 104.8, 106.2, 107.0, 106.5, 108.1, 109.3, 110.2],
                   index = pd.date_range('2023-01-01', periods=10))
print(prices)
a = prices.pct_change() #percent change （今-前）/前 1
print(a.idxmax())  #日期
print(a.idxmin())  #最低日期
print(a.std())  #波动率

2023-01-01    102.3
2023-01-02    103.5
2023-01-03    105.1
2023-01-04    104.8
2023-01-05    106.2
2023-01-06    107.0
2023-01-07    106.5
2023-01-08    108.1
2023-01-09    109.3
2023-01-10    110.2
Freq: D, dtype: float64
2023-01-03 00:00:00
2023-01-07 00:00:00
0.007373623845361105

In [59]:
#某产品过去12个月的销售量Series:
#计算季度平均销量(每3个月为一个季度)
#找出销量最高的月份
#计算月环比增长率 环比=（今-前）/前  同比=每年同期
# 找出连续增长超过2个月的月份
sales = pd.Series([120, 135, 145, 160, 155, 170, 180, 175, 190, 200, 210,
        220],index=pd.date_range('2022-01-01', periods=12, freq='MS')) #M=月
#季度平均销量
print(sales.resample('QS').mean()) # 重新采样 .sum() .median()
#销量最高的月份
print('销量最高的月份： ', sales.idxmax())
# 月环比增长率
print('月环比增长率')
print(sales.pct_change())
#连续增长超过两个月的月份
a = sales.pct_change()
b =a>0
print(b)
b[b.rolling(3).sum()==3].keys().tolist()

2022-01-01    133.333333
2022-04-01    161.666667
2022-07-01    181.666667
2022-10-01    210.000000
Freq: QS-JAN, dtype: float64
销量最高的月份：  2022-12-01 00:00:00
月环比增长率
2022-01-01         NaN
2022-02-01    0.125000
2022-03-01    0.074074
2022-04-01    0.103448
2022-05-01   -0.031250
2022-06-01    0.096774
2022-07-01    0.058824
2022-08-01   -0.027778
2022-09-01    0.085714
2022-10-01    0.052632
2022-11-01    0.050000
2022-12-01    0.047619
Freq: MS, dtype: float64
2022-01-01    False
2022-02-01     True
2022-03-01     True
2022-04-01     True
2022-05-01    False
2022-06-01     True
2022-07-01     True
2022-08-01    False
2022-09-01     True
2022-10-01     True
2022-11-01     True
2022-12-01     True
Freq: MS, dtype: bool

[Timestamp('2022-04-01 00:00:00'),
 Timestamp('2022-11-01 00:00:00'),
 Timestamp('2022-12-01 00:00:00')]

In [74]:
# 某商店每小时销售额Series:
# 按天重采样计算每日总销售额
# 计算每天营业时间(8:00-22:00)和非营业时间的销售额比例
# 找出销售额最高的3个小时
import pandas as pd
import numpy as np
np.random.seed(42)
hours_sales=pd.Series(np.random.randint(0, 100, 24),
          index=pd.date_range('2025-01-01', periods=24,freq='h'))
# 按天重采样计算每日总销售额
day_sales = hours_sales.resample('D').sum()
# hours_sales.sum()
# 计算每天营业时间(8:00-22:00)和非营业时间的销售额比例
# hours_sales.between_time('8:00', '22:00') # 筛选一段时间内额series
business_hours_sales = hours_sales[(hours_sales.index.hour>=8) & 
                                   (hours_sales.index.hour<=22)].sum()
print(business_hours_sales / (day_sales-business_hours_sales))
# 找出销售额最高的3个小时
print(hours_sales.nlargest(3))

2025-01-01    1.429435
Freq: D, dtype: float64
2025-01-01 11:00:00    99
2025-01-01 01:00:00    92
2025-01-01 10:00:00    87
dtype: int32