In [1]:
# dataframe的创建方式
import pandas as pd
import numpy as np

In [11]:
# 通过Series来创建
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({"第一列":s1, "第二列":s2})
#通过字典来创建
df = pd.DataFrame(
    {
        "name":["tom", "jack", "alice", "bob", "allen"],
        "age":[15, 17, 20, 26, 30],
        "score":[60.5, 80, 20, 70, 83.5],
    },index=[1,2,3,4,5],columns=["name", "score", "age"]
)
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30

In [ ]:
# dataframe的属性
print('行索引：')
print(df.index)
print('列标签：')
print(df.columns)
print('值：')
print(df.values)

行索引：
Index([1, 2, 3, 4, 5], dtype='int64')
列标签：
Index(['name', 'score', 'age'], dtype='str')
值：
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 20.0 20]
 ['bob' 70.0 26]
 ['allen' 83.5 30]]

In [17]:
print('维度：', df.ndim)
print('形状：', df.shape)
print('元素个数：', df.size)
print('数据类型：')
print(df.dtypes)

维度： 2
形状： (5, 3)
元素个数： 15
数据类型：
name         str
score    float64
age        int64
dtype: object

In [20]:
#行列转置
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30

In [ ]:
# 获取元素 loc iloc at iat
# 某行元素
print(df.loc[4])
print(df.iloc[4]) #隐式索引

name      bob
score    70.0
age        26
Name: 4, dtype: object
name     allen
score     83.5
age         30
Name: 5, dtype: object

In [25]:
# 某列数据
print(df.loc[:,'name'])
print(df.iloc[:,0])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

In [30]:
#单个元素
print(df)
print(df.at[3,'score'])
print(df.iat[2,1])
print(df.loc[3,'score'])

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30
20.0
20.0
20.0

In [39]:
# 获取单列数据
print(df[['name','score']])
print(type(df['name']))
print(df.name)
print(type(df.name))
print(df[['name']])
print(type(df[['name']]))

    name  score
1    tom   60.5
2   jack   80.0
3  alice   20.0
4    bob   70.0
5  allen   83.5
<class 'pandas.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.DataFrame'>

In [43]:
# 查看部分数据
print(df.head(2))
print(df.tail(3))

   name  score  age
1   tom   60.5   15
2  jack   80.0   17
    name  score  age
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30

In [47]:
#使用布尔索引筛选数据
df[df.score>70]
df[(df.score>70) & (df.age<20)]

   name  score  age
2  jack   80.0   17

In [56]:
# 随机抽样
df.sample(3)

    name  score  age
1    tom   60.5   15
4    bob   70.0   26
3  alice   20.0   20

In [57]:
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30

In [60]:
print(df.head(2)) # 查看前n行数据
print(df.tail(2))

   name  score  age
1   tom   60.5   15
2  jack   80.0   17
    name  score  age
4    bob   70.0   26
5  allen   83.5   30

In [ ]:
print(df.isin(['jack',20])) #查看元素是否在参数集合中

    name  score    age
1  False  False  False
2   True  False  False
3  False   True   True
4  False  False  False
5  False  False  False

In [ ]:
print(df.isna()) # 查看元素是否是缺失值

In [73]:
print(df['score'].sum()) # 某一列的总和
print(df.score.max())
print(df.age.min())
print(df.score.mean())
print(df.score.median())
print(df.age.mode())

314.0
83.5
15
62.8
70.0
0    15
1    17
2    20
3    26
4    30
Name: age, dtype: int64

In [ ]:
print(df.score.std())
print(df.score.var())
print(df.score.quantile(0.25))

25.560223003722015
653.325
60.5

In [77]:
print(df.describe())

           score        age
count   5.000000   5.000000
mean   62.800000  21.600000
std    25.560223   6.268971
min    20.000000  15.000000
25%    60.500000  17.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.500000  30.000000

In [ ]:
print(df.count()) #每一列非缺失值的个数

name     5
score    5
age      5
dtype: int64

In [ ]:
print(df.value_counts()) # 出现的频率

name   score  age
tom    60.5   15     1
jack   80.0   17     1
alice  20.0   20     1
bob    70.0   26     1
allen  83.5   30     1
Name: count, dtype: int64

In [ ]:
print(df.drop_duplicates()) #查看是否重复

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30

In [83]:
print(df.duplicated(subset=['age']))

1    False
2    False
3    False
4    False
5    False
dtype: bool

In [85]:
df.sample(2)

   name  score  age
2  jack   80.0   17
4   bob   70.0   26

In [86]:
print(df.replace(15,30))

    name  score  age
1    tom   60.5   30
2   jack   80.0   17
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30

In [87]:
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   20.0   20
4    bob   70.0   26
5  allen   83.5   30

In [ ]:
df.cumsum() #累积
df.cummin(axis=0) #0行1列

    name  score  age
1    tom   60.5   15
2   jack   60.5   15
3  alice   20.0   15
4  alice   20.0   15
5  alice   20.0   15

In [94]:
print(df.sort_index(ascending=False))

    name  score  age
5  allen   83.5   30
4    bob   70.0   26
3  alice   20.0   20
2   jack   80.0   17
1    tom   60.5   15

In [98]:
print(df.sort_values(by=['score','age']))

    name  score  age
3  alice   20.0   20
1    tom   60.5   15
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [101]:
df.nlargest(2,columns=['score'])
df.nsmallest(2,columns=['age'])

   name  score  age
1   tom   60.5   15
2  jack   80.0   17

In [134]:
import pandas as pd
data = {
    '姓名':['张三','李四','王五','赵六','钱七'],
    '数学':[85,92,78,88,95],
    '英语':[90,88,85,92,80],
    '物理':[75,80,88,85,90]
}
scores = pd.DataFrame(data)

#场景:某班级的学生成绩数据如下，请完成以下任务:
#1.计算每位学生的总分和平均分。
scores['总分'] = scores[['数学','英语','物理']].sum(axis=1).to_frame()
scores['平均分'] = scores['总分'] / 3
scores
#2.找出数学成绩高于90分或英语成绩高于85分的学生。
scores[(scores['数学']> 90) | (scores['英语']>85)]
#3.按总分从高到低排序，并输出前3名学生。
r1 = scores.sort_values('总分',ascending=False).head(3)
display(r1)
r2 = scores.nlargest(3,columns=['总分'])
display(r2)

   姓名  数学  英语  物理   总分        平均分
4  钱七  95  80  90  265  88.333333
3  赵六  88  92  85  265  88.333333
1  李四  92  88  80  260  86.666667

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

In [141]:
#销售数据分析
#场景:某公司销售数据如下，请完成以下任务:
#1.计算每种产品的总销售额(销售额=单价x销量)。
#2.找出销售额最高的产品。
#3.按销售额从高到信序并输出所有产品信息。
import pandas as pd
data = {
'产品名称':['A','B','C','D'],
'单价':[100,150,200,120],
'销量': [50, 30, 20, 40]
}
df = pd.DataFrame(data)
df['总销售额'] = df['单价']*df['销量']
df.nlargest(1, columns=['总销售额'])
df.sort_values('总销售额',ascending=False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [151]:
#1.计算每位用户的总消费金额(消费金额=商品单价x购买数量)
#2.找出消费金额最高的用户，并输出其所有信息
#3.计算所有用户的平均消费金额(保留2位小数)
#4.统计电子产品的总购买数量
import pandas as pd
data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名':['Alice','Bob','Charlie','David','Eve'],
'商品类别':['电子产品','服饰','电子产品','家居','服饰'],
'商品单价':[1200,300,800,150,200],
'购买数量':[1,3,2,5,4],
}
df = pd.DataFrame(data)
df['总消费金额'] = df['商品单价']*df['购买数量']
display(df)
max = df.nlargest(1,columns='总消费金额')
display(max)
mean = df['总消费金额'].mean()
print(mean)
df[df['商品类别']=='电子产品']['购买数量'].sum()

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
0   101    Alice  电子产品  1200     1   1200
1   102      Bob    服饰   300     3    900
2   103  Charlie  电子产品   800     2   1600
3   104    David    家居   150     5    750
4   105      Eve    服饰   200     4    800

   用户ID      用户名  商品类别  商品单价  购买数量  总消费金额
2   103  Charlie  电子产品   800     2   1600

1050.0

np.int64(3)